### ISSUE TITLE
Question on /c/dynamic-array.c

### ISSUE THREAD

**Issue by nyngwang** [wrp/examples#1]
https://github.com/wrp/examples/blob/64743c160b32e2bd42dc136a9b041f7b2b05ea8a/c/dynamic-array.c#L37

If one pop some chars front the buffer, so `a->start` will be incremented, then my question is: When resizing the buffer I assume that one would need the original position of `a->start`, but it already changed?

https://github.com/wrp/examples/blob/64743c160b32e2bd42dc136a9b041f7b2b05ea8a/c/dynamic-array.c#L44

(A reader from StackOverflow, want to learn from your code, thanks in advance!)

**Comment by wrp** [comment]
Sorry for the long delay; I didn't see this question until just now.  I need to check github notifications more frequently, it would seem!  The original location of the memory is stored in `a->data`, so it is safe to increment `a->start`.  All the reallocs are applied to `a->data`, and `a->start` is just a place holder into the correct location in the buffer.

**Comment by nyngwang** [comment]
Now, this is my thanks! (Stay safe during the epidemic!)
